#!/bin/bash
# GitHub Release Automation
# Usage: create-release owner/repo tag [title]

REPO="$1"
TAG="$2"
TITLE="${3:-Release $TAG}"

if [ -z "$REPO" ] || [ -z "$TAG" ]; then
    echo "Usage: create-release owner/repo tag [title]"
    exit 1
fi

echo "🏷️  Creating release $TAG for $REPO..."

# Check if tag exists
if ! gh api "repos/$REPO/git/ref/tags/$TAG" >/dev/null 2>&1; then
    echo "❌ Tag $TAG does not exist. Create it first:"
    echo "   git tag $TAG"
    echo "   git push origin $TAG"
    exit 1
fi

# Get commits since last tag
LAST_TAG=$(gh release view --repo "$REPO" --json tagName --jq '.tagName' 2>/dev/null || echo "")

if [ -n "$LAST_TAG" ]; then
    echo "📊 Changes since $LAST_TAG:"
    COMMITS=$(git log "$LAST_TAG..$TAG" --pretty=format:"- %s (%h)" 2>/dev/null || echo "")
else
    echo "📊 Recent changes:"
    COMMITS=$(git log "$TAG" --pretty=format:"- %s (%h)" -20 2>/dev/null || echo "")
fi

# Categorize commits
FEATURES=$(echo "$COMMITS" | grep -iE "^.*(feat|feature|add):" || echo "")
FIXES=$(echo "$COMMITS" | grep -iE "^.*(fix|bug|hotfix):" || echo "")
DOCS=$(echo "$COMMITS" | grep -iE "^.*(doc|docs):" || echo "")
REFACTOR=$(echo "$COMMITS" | grep -iE "^.*(refactor|cleanup):" || echo "")
OTHER=$(echo "$COMMITS" | grep -viE "^.*(feat|feature|add|fix|bug|hotfix|doc|docs|refactor|cleanup):" || echo "")

# Build release notes
NOTES="## What's New

"

if [ -n "$FEATURES" ]; then
    NOTES="${NOTES}### ✨ Features
$FEATURES

"
fi

if [ -n "$FIXES" ]; then
    NOTES="${NOTES}### 🐛 Bug Fixes
$FIXES

"
fi

if [ -n "$DOCS" ]; then
    NOTES="${NOTES}### 📚 Documentation
$DOCS

"
fi

if [ -n "$REFACTOR" ]; then
    NOTES="${NOTES}### 🔧 Refactoring
$REFACTOR

"
fi

if [ -n "$OTHER" ]; then
    NOTES="${NOTES}### 📝 Other Changes
$OTHER

"
fi

NOTES="${NOTES}---
🤖 Auto-generated by OpenClaw"

# Create release
echo ""
echo "🚀 Creating release..."
if gh release create "$TAG" \
    --repo "$REPO" \
    --title "$TITLE" \
    --notes "$NOTES"; then
    echo "✅ Release $TAG created successfully!"
else
    echo "❌ Failed to create release"
    exit 1
fi
